language: node_js
node_js:
  - "6"
  - "8"
  - "10"

before_install:
  - npm install -g grunt-cli

before_script:
  - npm install -g bower
  - bower update

#travis build  speed up
sudo: false
cache:
  directories:
    - node_modules
    - bower_components

# scripts
script: grunt test